### ISSUE TITLE
initial seed of repositories

### ISSUE THREAD

**Issue by hannesm** [rudenoise/mirage-dashboard#2]
https://github.com/mirage/mirage-www/blob/master/TROVE

**Comment by amirmc** [comment]
TROVE is also a little out of date. A quick review and PR for any new libs would be very welcome :)

**Comment by rudenoise** [comment]
I've added a json file to act as a data source.

https://raw.githubusercontent.com/rudenoise/mirage-dashboard/master/data/repos.json

It should be pretty simple/flexible and managing it will be a manual (PR) process for the time being.

The tags will be handy for filtering the data shown on the dashboard.

Hope this isn't unnecessary duplication?

**Comment by avsm** [comment]
This is completely awesome -- don't worry about duplication, as we can adopt whatever format you choose.
