### ISSUE TITLE
random notes

### ISSUE THREAD

**Issue by hannesm** [rudenoise/mirage-dashboard#3]
- here's cosmetrics, which gathered some statistics of OCaml projects https://github.com/ocamllabs/cosmetrics
- what I really would like to see is a list of mirage projects
  - name
  - license
  - last release (version + date)
  - commits to master since last release
  - open issues (maybe more detailed numbers from labels)
  - open PRs
  - branches (maybe active only? some mirage repos have way too many stale branches)
  - top 3 contributors
  - CI status
  - last activity: commit / issue

**Comment by rudenoise** [comment]
Cool, I've updated the TO DO list.

Will checkout cosmetrics too.

**Comment by hannesm** [comment]
thx.. closing this since it is part of the TODO :)
