### ISSUE TITLE
Capture version tags as releases

### ISSUE THREAD

**Issue by dsheets** [rudenoise/mirage-dashboard#5]
A lot of projects don't use the GitHub Release API (it's just another step in the release process and hasn't been thoroughly automated yet) so it would be nice to grab tags that look like version numbers, too.

**Comment by rudenoise** [comment]
The dashboard now fetches releases and tags.

No releases falls back to tags.

No tags falls back to default "none yet message"

http://rudenoise.github.io/mirage-dashboard/

**Comment by dsheets** [comment]
Nice work! I see c9647053630bc86ad8aa3f32e879548f50830d70 looks like the relevant commit?

One enhancement would be to compare the timestamps on the latest release and the latest tag and use the newer of the two. This is relevant for repositories like https://github.com/mirage/ocaml-ipaddr/releases. I can't recall what timestamp formats are in use so this may require adopting a dependency on a library if they aren't both RFC 3339 or whatever. Off the top of my head, I think RFC 3339 timestamps are comparable lexicographically.

**Comment by hannesm** [comment]
@dsheets yes, RFC3339 can be ordered lexicographically (see https://tools.ietf.org/html/rfc3339#section-5.1) (if same timezone is used etc.)

**Comment by rudenoise** [comment]
@dsheets @hannesm is this the right thing to do?

The github-release contains much more descriptive data but is it the tag that usually ends up in opam?

Would this be compensating for the wrong behaviour or is this the common case?

**Comment by dsheets** [comment]
I don't think we can ensure that Mirage projects always create GitHub releases but improvements like https://github.com/OCamlPro/opam-publish/issues/41 will help. I think if there is a more recent version-like tag than the most recent release, it is probably the most recent publication.

Another option is to interface with `opam-lib` and extract the latest version of the library from the `ocaml/opam-repository` itself but this is much more complicated than date comparison. @hannesm? @avsm?

**Comment by hannesm** [comment]
my humble opinion is that dashboard needs some information from opam files anyways, and thus we should extract the version number also via opam ;) [other information such as tags/maybe changelog/maintainer/author/dependencies?]

I'd think for now date comparison is fine, and once we've a better view what we want we can still switch over to opam information...

**Comment by rudenoise** [comment]
@dsheets @hannesm I've added the comparison of tag and release date, the data returned now replaces the release with a tag when its date is greater.
